AllCops:
  TargetRubyVersion: 3.0.5
  NewCops: enable
  SuggestExtensions: false
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "*.gemspec"
Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 14
